// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFSKUmLeZPrHwl-YvqzaGCNbeASDUh2iI',
    appId: '1:996851553930:web:43355c7477c32dea783f73',
    messagingSenderId: '996851553930',
    projectId: 'supervision-59383',
    authDomain: 'supervision-59383.firebaseapp.com',
    databaseURL: 'https://supervision-59383-default-rtdb.firebaseio.com',
    storageBucket: 'supervision-59383.appspot.com',
    measurementId: 'G-C0QRZPL49J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0e1-wenBJR60EwKQ_HXBogYQwa4FXj1U',
    appId: '1:996851553930:android:ffde19523869a06e783f73',
    messagingSenderId: '996851553930',
    projectId: 'supervision-59383',
    databaseURL: 'https://supervision-59383-default-rtdb.firebaseio.com',
    storageBucket: 'supervision-59383.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-9QQ3rjYYVkpZ4U-HAWLG6mBzm3oeGLU',
    appId: '1:996851553930:ios:21ce4f4bf75c85ca783f73',
    messagingSenderId: '996851553930',
    projectId: 'supervision-59383',
    databaseURL: 'https://supervision-59383-default-rtdb.firebaseio.com',
    storageBucket: 'supervision-59383.appspot.com',
    androidClientId: '996851553930-34b8cjgj3jnngjefa51st68t7a4aai18.apps.googleusercontent.com',
    iosClientId: '996851553930-05iaou9o6rmk831vhml8iaoupcvu4ul5.apps.googleusercontent.com',
    iosBundleId: 'com.example.sampleproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-9QQ3rjYYVkpZ4U-HAWLG6mBzm3oeGLU',
    appId: '1:996851553930:ios:21ce4f4bf75c85ca783f73',
    messagingSenderId: '996851553930',
    projectId: 'supervision-59383',
    databaseURL: 'https://supervision-59383-default-rtdb.firebaseio.com',
    storageBucket: 'supervision-59383.appspot.com',
    androidClientId: '996851553930-34b8cjgj3jnngjefa51st68t7a4aai18.apps.googleusercontent.com',
    iosClientId: '996851553930-05iaou9o6rmk831vhml8iaoupcvu4ul5.apps.googleusercontent.com',
    iosBundleId: 'com.example.sampleproject',
  );
}
